### ISSUE TITLE
How query logs should be queued for batch INSERT INTO?

### ISSUE THREAD

**Issue by ghalimi** [sutoiku/puffin#1]
Every query must be [logged](https://github.com/sutoiku/puffin/blob/main/docs/Logs.md) into an [Iceberg table](https://iceberg.apache.org/spec/) using an [`INSERT INTO`](https://iceberg.apache.org/docs/latest/spark-writes/#insert-into) query. Batching multiple such queries into one would make it more efficient, but would require some queuing mechanism. Since low latency is not an absolute requirement for query logs, [Amazon SQS](https://aws.amazon.com/sqs/) could be used for such a purpose, but should other options be considered?

**Comment by ghalimi** [comment]
Using an Iceberg table for logs is probably adding more complexity than is necessary. [Amazon ElastiCache for Redis](https://aws.amazon.com/elasticache/redis/) is probably a better option.

**Comment by alexey-milovidov** [comment]
I don't think it's the best approach. For example, ClickHouse logs the queries directly into ClickHouse (itself) into the `system.query_log` table. That's how they can be analyzed with low latency.

**Comment by ghalimi** [comment]
We're actually going in that direction now.
