### ISSUE TITLE
What would be the best way to integrate a client-side DuckDB engine with PuffinDB?

### ISSUE THREAD

**Issue by ghalimi** [sutoiku/puffin#4]
Moving forward, [DuckDB](https://duckdb.org/) will be found everywhere, both client-side and cloud-side. When used client-side, what would be the best way to integrate it with PuffinDB running cloud-side? As a developer, I would like to make a query from my DuckDB client, have it executed cloud-side by PuffinDB, have its result streamed with [Apache Arrow](https://arrow.apache.org/) to my client, and have that result saved as a local [Apache Parquet](https://parquet.apache.org/) file, or loaded into my local DuckDB client with a `CREATE TABLE`. With that in mind, what needs to be changed in DuckDB to make that dataflow as seamless as possible?

And could this dataflow be further improved upon?

**Comment by ghalimi** [comment]
My preferred solution would be a syntax like `SELECT REMOTE`:

`SELECT REMOTE 'https://myPuffinService.com/' * FROM myRemoteTable`

With that syntax, `myRemoteTable` is local to `https://myPuffinService.com/`.

**Comment by davidgasquez** [comment]
The folks at seafowl did something similar recently here: https://github.com/splitgraph/seafowl/tree/main/datafusion_remote_tables. Having that and some extra FDWs in DuckDB would be incredible for the Open Data movement.

**Comment by ghalimi** [comment]
> The folks at seafowl did something similar recently here: https://github.com/splitgraph/seafowl/tree/main/datafusion_remote_tables. Having that and some extra FDWs in DuckDB would be incredible for the Open Data movement.

Exactly!

**Comment by ghalimi** [comment]
We should also consider using [Apache Arrow Flight SQL](https://arrow.apache.org/blog/2022/02/16/introducing-arrow-flight-sql/).

This idea was [suggested](https://twitter.com/changhiskhan/status/1617002146461020160) by [@changhiskhan](https://twitter.com/changhiskhan).

**Comment by ghalimi** [comment]
A more detailed introduction is available there: [Edge-Driven Data Integration](https://github.com/sutoiku/puffin/blob/main/EDDI.md)

**Comment by alexey-milovidov** [comment]
ClickHouse has the notion of Distributed tables - it makes it possible to run heavy computations on the server side in a distributed fashion and finish the computation on the local machine, which can be located at the edge.

**Comment by ghalimi** [comment]
> ClickHouse has the notion of Distributed tables - it makes it possible to run heavy computations on the server side in a distributed fashion and finish the computation on the local machine, which can be located at the edge.

Good to know.
