### ISSUE TITLE
Should we consider adding support for CloudFront to cache certain query results?

### ISSUE THREAD

**Issue by ghalimi** [sutoiku/puffin#6]
By default, query results will be cached on the Object Store (S3 on AWS). But query results that are requested often could be cached using [Amazon CloudFront](https://aws.amazon.com/cloudfront/).

This idea was originally [suggested](https://twitter.com/TobiM/status/1616939432489140225) by [@TobiM](https://twitter.com/TobiM).

**Comment by tobilg** [comment]
This would require auth headers support in the httpfs module, and using CloudFront functions or Lambda@Edge functions to validate the auth info.

**Comment by tobilg** [comment]
See https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/RequestAndResponseBehaviorS3Origin.html

**Comment by ghalimi** [comment]
This is super cool. Now, if we want to take advantage of that feature, the client making requests to PuffinDB will need to fetch cached results directly from an S3 origin. That means that we should add that feature when working on `SELECT REMOTE`.

**Comment by ghalimi** [comment]
This seems like a no-brainer. This feature has been added to the [roadmap](https://github.com/sutoiku/puffin/blob/main/ROADMAP.md).

**Comment by tobilg** [comment]
As reference, I created a feature request for DuckDB here: https://github.com/duckdb/duckdb/discussions/5972

**Comment by ghalimi** [comment]
Awesome! Thanks a lot @tobilg.
