### ISSUE TITLE
Should we use Apache Calcite or Substrait?

### ISSUE THREAD

**Issue by ghalimi** [sutoiku/puffin#7]
PuffinDB will include a distributed query planner. This complex component should probably be developed on top of an existing framework implementing a [relational algebra](https://en.wikipedia.org/wiki/Relational_algebra). The two main options are [Apache Calcite](https://calcite.apache.org/) and [Substrait](https://substrait.io/). Which one should we use? Either should work, but we must pick one. This decision will have major and lasting impacts on the codebase.

**Comment by ghalimi** [comment]
We should probably use [Apache Calcite](https://calcite.apache.org/), for the following reasons:

- Much more mature
- Much more aligned with our needs
- Powerful [relational algebra](https://calcite.apache.org/docs/algebra.html)
- Extensive collection of [adapters](https://calcite.apache.org/docs/adapter.html)
- Support for [streaming](https://calcite.apache.org/docs/stream.html)
- Support for [materialized views](https://calcite.apache.org/docs/materialized_views.html)
- Support for [lattices](https://calcite.apache.org/docs/lattice.html)

**Comment by jacques-n** [comment]
They aren't really substitutes for each other. In fact, one of the goals for Substrait was to provide a clean cross-language api into Calcite. 

Integrating with Calcite across language barriers can be rough (check out dask sql which actually switched to datafusion because of the pain). Substrait tries to create a standard algebraic facade to be used amongst multiple systems. There is already a bunch of work for Substrait <> Calcite integration in the substrait-java repo but there are also integration with other techs like Datafusion (rust system that is basically Calcite-lite) as well dplyr, ibis, etc.

**Comment by ghalimi** [comment]
@jacques-n Thanks a lot for that. I realize that Calcite and Substrait have different goals, and I really like where Substrait is going. But I don't think Substrait gives us what we need today. DataFusion looks like a great alternative though. But that means yet another Lambda function (one for Iceberg's Java API, one for DataFusion, and one for the query API). Unless we implement the query API in Rust instead of Node.js. Interesting challenge...

**Comment by ghalimi** [comment]
@jacques-n How about leveraging Ballista's distributed query planner?

**Comment by jacques-n** [comment]
I'm not super close to Ballista. @AndyGrove would be a better person to comment.

**Comment by ghalimi** [comment]
@jacques-n Thanks for the tip. I will ask him.

**Comment by davidgasquez** [comment]
Sharing this great repository: https://github.com/cloudfuse-io/lambdatization. They've been running ballista/datafusion in Lambdas and might be useful for you.

**Comment by ghalimi** [comment]
@davidgasquez Thanks a lot for sharing this. Super helpful!

**Comment by ghalimi** [comment]
@andygrove Thank you so much. This is immensely helpful. If I understand what you wrote correctly, my feeling is that we should use DataFusion and get some inspiration from Ballista regarding the distributed query planner. Or work on adding support for Substrait in Ballista. I still need to wrap my head around what Substrait really does, but a picture is starting to form. And using DataFusion for implementing our query planner would also add the option of running the DataFusion query engine side-by-side with DuckDB on the cloud, which is really attractive, for a host of different reasons.

Thank you, very much.

**Comment by andygrove** [comment]
I tend to think of substrait as "just" a standardized protobuf representation of a query plan. This solves a few problems:

- Makes it possible to use Calcite (JVM) to produce plans that are then consumed in other languages
- Make it easier to send query plans over the network without having to build custom implementations
- Make it possible to mix and match query planning and query execution libraries

To expand more on why DataFusion's Arrow support might be interesting, here is an example of interoperability between DuckDB and DataFusion (via PyArrow).

https://duckdb.org/docs/guides/python/datafusion.html

**Comment by ghalimi** [comment]
That makes a ton of sense. And thank you for the link. From what I gather, we could package both DataFusion and DuckDB within the same Rust Lambda (I'll call it the `Engine` Lambda), while having Iceberg's Java API in a separate Java Lambda (the `Lakehouse` Lambda).

Any query would be handled by the `Engine` Lambda, which would implement a distributed query planner in Rust, using APIs from DataFusion (and Ballista?). The query planner would then invoke the same `Engine` Lambda in a recursive manner, using either DataFusion or DuckDB as core query engine, depending on the specifics of the query. I assume that DataFusion and DuckDB will be neck and neck on the cloud side, with one being better at some queries than the other, having both would be really nice.

Now, here is the trick question: for the distributed query planner itself, how much should we try to reuse from Ballista? Being fully serverless and using Redis for queuing and synchronization, I assume that our distributed execution model will be quite different from a plumbing standpoint, but the logical distribution should be very similar. Any recommendations there?

Thanks again for your help, this is totally priceless.

**Comment by ghalimi** [comment]
After more research, I believe that we should build this query planner using DuckDB itself. This [page](https://github.com/sutoiku/puffin/blob/main/docs/Query%20Planner.md) outlines a possible approach.
