### ISSUE TITLE
SELECT THROUGH

### ISSUE THREAD

**Issue by snth** [sutoiku/puffin#9]
In EDDI.md you propose a `SELECT THROUGH` syntax (I think this was previously SELECT REMOTE) like
```sql
SELECT THROUGH 'https://myPuffinDB.com/' * FROM remoteTable;
```

I would suggest that you rather make `THROUGH` a separate clause since while the current proposal might read more naturally, IMHO it doesn't make so much sense semantically since it sits inside the `SELECT` clause. The `SELECT` clause should be about specifying the projections of the relation and it's not clear to me that `THROUGH` relates to that.

The following still reads like sensible English while having more semantic separation:
```sql
THROUGH 'https://myPuffinDB.com/' SELECT * FROM remoteTable;
```

**Comment by ghalimi** [comment]
You are absolutely correct. I realized exactly the same when going to bed yesterday night, and forgot to fix it today. The original proposal makes no semantic sense at all. But it should be done like that if we want nesting (which we do):

```
SELECT * THROUGH 'https://myPuffinDB.com/' FROM remoteTable;
```

**Comment by ghalimi** [comment]
Fixed there, with due credits:

https://github.com/sutoiku/puffin/blob/main/EDDI.md

**Comment by snth** [comment]
Ok, happy to keep it there. Thank you 😊

**Comment by alexey-milovidov** [comment]
ClickHouse implements it with the table function `view`. It allows offloading of an arbitrary part of the computation to a remote server or a cluster.

**Comment by ghalimi** [comment]
That's an interesting approach. Can you provide a sample query using it?

**Comment by alexey-milovidov** [comment]
```
SELECT ... FROM remote('remote server or a cluster', view(SELECT ... /* a query sent to the remote server */))
```

**Comment by ghalimi** [comment]
Thanks!
